-- AlterEnum: Remove STORYBOARD_FRAME from BlockType
BEGIN;
CREATE TYPE "BlockType_new" AS ENUM ('PARAGRAPH', 'HEADING_1', 'HEADING_2', 'HEADING_3', 'BULLETED_LIST', 'NUMBERED_LIST', 'CALLOUT', 'PERFORMANCE_PROBLEM', 'INSTRUCTIONAL_GOAL', 'TASK_STEP', 'LEARNING_OBJECTIVE', 'ASSESSMENT_IDEA', 'STORYBOARD_METADATA', 'CONTENT_SCREEN', 'LEARNING_OBJECTIVES_IMPORT');
ALTER TABLE "blocks" ALTER COLUMN "type" TYPE "BlockType_new" USING ("type"::text::"BlockType_new");
ALTER TYPE "BlockType" RENAME TO "BlockType_old";
ALTER TYPE "BlockType_new" RENAME TO "BlockType";
DROP TYPE "public"."BlockType_old";
COMMIT;
