-- Rename NEW_SYSTEM to TOOL_AND_PROCESS in both enums
ALTER TYPE "CourseType" RENAME VALUE 'NEW_SYSTEM' TO 'TOOL_AND_PROCESS';
ALTER TYPE "TrainingType" RENAME VALUE 'NEW_SYSTEM' TO 'TOOL_AND_PROCESS';
